// <auto-generated />
using System;
using CreditEngine.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditEngine.Infrastructure.Migrations
{
    [DbContext(typeof(CreditEngineDbContext))]
    [Migration("20260128191919_SeedCompanies")]
    partial class SeedCompanies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditEngine.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualRevenue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cash")
                        .HasColumnType("numeric");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Ebitda")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AnnualRevenue = 1800000m,
                            Cash = 200000m,
                            Cnpj = "12.345.678/0001-90",
                            Ebitda = 360000m,
                            TotalDebt = 500000m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AnnualRevenue = 600000m,
                            Cash = 50000m,
                            Cnpj = "98.765.432/0001-10",
                            Ebitda = 90000m,
                            TotalDebt = 150000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AnnualRevenue = 3600000m,
                            Cash = 400000m,
                            Cnpj = "45.987.321/0001-55",
                            Ebitda = 900000m,
                            TotalDebt = 1200000m
                        });
                });

            modelBuilder.Entity("CreditEngine.Domain.Entities.CreditDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CreditDecisions");
                });
#pragma warning restore 612, 618
        }
    }
}
